import Head from 'next/head'
import Banner from '../components/Banner'
import mainBanners from '../content/mainBanners'
import texts from '../content/texts'
import { Navigation, Pagination } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'
import LinesContainer from '../components/LinesContainer'
import DiscoverBanner from '../components/DiscoverBanner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>{texts.aiwaElec}</title>
        <meta name="title" content="Aiwa Electronics"></meta>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Swiper
          tag='section'
          className='main-banner'
          modules={[Navigation, Pagination]}
          loop
          navigation
          pagination={{ clickable: true }}
        >
          {mainBanners.map((e,i) => (
            <SwiperSlide key={i} className='main-banner-slide'>
              <Banner link={e.link} image={e.image} mobile={e.mobile} alt={e.title}/>
            </SwiperSlide>
          ))}
        </Swiper>
        <LinesContainer />
        <DiscoverBanner />
      </main>
    </div>
  )
}