import Head from 'next/head'
import texts from '../content/texts'
import Footer from '../components/Footer'
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>{texts.aiwaElec}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        Página principal de Aiwa Electronics2
      </main>
      <Footer />
    </div>
  )
}